snap: avoid using `source` for the content slot
MirServer/mesa-core22 pull request #5
Opened 2023-05-12 09:56 UTC by Saviq

It's geared at multi-provider use, which we don't support.

2023-05-15 11:45 UTC, AlanGriffiths requested changes
It isn't immediately obvious why, but...

```
$ ubuntu-frame
...
+ exec /snap/ubuntu-frame/5338/bin/graphics-core22-wrapper /snap/ubuntu-frame/5338/usr/local/bin/frame
/snap/ubuntu-frame/5338/usr/local/bin/frame: error while loading shared libraries: libwayland-client.so.0: cannot open shared object file: No such file or directory
```

2023-05-15 11:55 UTC, AlanGriffiths commented
> It isn't immediately obvious why, but...

...the reason is:

before:
```
$ find $SNAP/graphics/ -name libwayland-client.so.0
/snap/ubuntu-frame/5338/graphics/lib/i386-linux-gnu/libwayland-client.so.0
/snap/ubuntu-frame/5338/graphics/lib/x86_64-linux-gnu/libwayland-client.so.0
```

after:
``
`$ find $SNAP/graphics/ -name libwayland-client.so.0
/snap/ubuntu-frame/5338/graphics/usr/lib/i386-linux-gnu/libwayland-client.so.0
/snap/ubuntu-frame/5338/graphics/usr/lib/x86_64-linux-gnu/libwayland-client.so.0
```

Note the addition of `/usr` under `graphics`

2023-05-15 12:13 UTC, Saviq commented
> Note the addition of `/usr` under `graphics`

Good catch. Fixed.

2023-05-15 17:08 UTC, merged

2023-05-25 08:39 UTC, AlanGriffiths commented
> > This reorganises the snap contents (we get `$SNAP/graphics/usr/{lib,share}` where we used to have `$SNAP/graphics/{lib,share}`). I don't think that breaks any promises we've documented, but it could be surprising.
> 
> Right, but part of the idea was that this layout is _not_ part of the interface contract.

Oops! This contradicts https://mir-server.io/docs/the-graphics-core22-snap-interface:

> [lay out](https://snapcraft.io/docs/snap-layouts) these paths in your snap:
> ```
> layout:
>   /usr/share/libdrm:
>     bind: $SNAP/graphics/usr/share/libdrm
>   /usr/share/drirc.d:
>     symlink: $SNAP/graphics/usr/share/drirc.d
> ```

https://discourse.ubuntu.com/t/the-graphics-core22-snap-interface/34663/2

2023-06-12 10:47 UTC, AlanGriffiths commented
> I said above that **this** layout is not part of the interface

Yeah, I fixed the docs